typedef EntityJsonEncoder = Map<String, dynamic> Function(Object value);

/// Runtime registry for entity JSON encoders generated by Loxia.
final class EntityJsonRegistry {
  EntityJsonRegistry._();

  static final Map<Type, EntityJsonEncoder> _encoders =
      <Type, EntityJsonEncoder>{};

  /// Registers an encoder for [T].
  static void register<T>(Map<String, dynamic> Function(T value) encoder) {
    _encoders[T] = (value) => encoder(value as T);
  }

  /// Tries to encode [value] using a registered encoder.
  static Map<String, dynamic>? tryEncode(Object value) {
    final encoder = _encoders[value.runtimeType];
    if (encoder == null) return null;
    return encoder(value);
  }

  /// Returns `true` when an encoder for [type] exists.
  static bool isRegistered(Type type) => _encoders.containsKey(type);
}
