typedef EntityJsonEncoder = Map<String, dynamic> Function(Object value);
typedef EntityJsonDecoder = Object? Function(Object? value);

/// Runtime registry for entity JSON encoders generated by Loxia.
final class EntityJsonRegistry {
  EntityJsonRegistry._();

  static final Map<Type, EntityJsonEncoder> _encoders =
      <Type, EntityJsonEncoder>{};
  static final Map<Type, EntityJsonDecoder> _decoders =
      <Type, EntityJsonDecoder>{};

  /// Registers an encoder for [T].
  static void register<T>(Map<String, dynamic> Function(T value) encoder) {
    _encoders[T] = (value) => encoder(value as T);
  }

  /// Registers a decoder for [T].
  static void registerDecoder<T>(T Function(Object? value) decoder) {
    _decoders[T] = decoder;
  }

  /// Tries to encode [value] using a registered encoder.
  static Map<String, dynamic>? tryEncode(Object value) {
    final encoder = _encoders[value.runtimeType];
    if (encoder == null) return null;
    return encoder(value);
  }

  /// Decodes [value] using a registered decoder for [T], or falls back to a cast.
  static T decode<T>(Object? value) {
    final decoder = _decoders[T];
    if (decoder != null) {
      return decoder(value) as T;
    }
    return value as T;
  }

  /// Returns `true` when an encoder for [type] exists.
  static bool isRegistered(Type type) => _encoders.containsKey(type);

  /// Returns `true` when a decoder for [type] exists.
  static bool isDecoderRegistered(Type type) => _decoders.containsKey(type);
}
