/// Runtime descriptor for a composite unique constraint.
///
/// This is the runtime counterpart of the [UniqueConstraint] annotation,
/// generated by the code generator and used by the migration planner.
class UniqueConstraintDescriptor {
  /// The list of column names that form the unique constraint.
  final List<String> columns;

  /// Optional constraint name. If null, one will be auto-generated
  /// based on the table and column names.
  final String? name;

  const UniqueConstraintDescriptor({required this.columns, this.name});

  /// Generates a default constraint name based on the table name.
  String generateName(String tableName) {
    return name ?? 'uq_${tableName}_${columns.join('_')}';
  }
}
